### ISSUE TITLE
it seems not work 

### ISSUE THREAD

**Issue by quhung** [y85171642/SpiderX#1]
Exception in thread "SpThreadCtrl -- " java.lang.NullPointerException
    at com.shit.tools.SpThreadCtrl.run(SpThreadCtrl.java:37)
    at java.lang.Thread.run(Thread.java:745)

**Comment by psygames** [comment]
Hi,you should install the mongoDB and create some collections(like mysql table)
Then i will Upload the file about mongoDB collections struction,
THX for your commetion .
